const seed = [
  ['Core CS',['DSA','C++','Java','Python','JavaScript','TypeScript','OOP','DBMS','SQL','Operating Systems','Computer Networks']],
  ['Development',['HTML','CSS','React.js','Node.js','Express.js','REST API','Authentication','Authorization','JWT','API Integration','React Router','React Query','Responsive Design']],
  ['Databases',['MySQL','MongoDB','Database Design','NoSQL']],
  ['AI & ML',['AI Fundamentals','LLM','Prompt Engineering','OpenAI API','Embeddings','Vector Search','RAG','Cosine Similarity','AI Application Development']],
  ['Cloud & DevOps',['AWS','Cloud Computing','CI/CD','Docker','Git','GitHub','Deployment','Vercel','Railway']],
  ['Tools & Placement',['JIRA','Confluence','Splunk','SPL','All about Internship','All about Projects','All about Hackathons','Aptitude','Guesstimate','Communication','HR Questions','Company-Specific Preparation','Mock Interviews']]
];
const quotes=[['You do not have to be great to start. You have to start to be great.','Today is the only preparation session that matters.'],['The interview is won long before the interview room.','Keep your promises to your future self.'],['Consistency turns difficult into familiar.','One checkbox. One topic. One edge.'],['Your preparation is a vote for the career you want.','Make today count.']];
const $=s=>document.querySelector(s);let timer=1500,timerId=null,editingId=null;
const newTopic=(name,category)=>({id:crypto.randomUUID(),name,category,done:false,completedAt:null});
const defaultState=()=>({companies:[{id:'master',name:'Master preparation',topics:seed.flatMap(([category,names])=>names.map(name=>newTopic(name,category)))}],active:'master',activity:[]});
let state;try{state=JSON.parse(localStorage.getItem('placement-momentum'))||defaultState()}catch{state=defaultState()}
const save=()=>localStorage.setItem('placement-momentum',JSON.stringify(state));
const active=()=>state.companies.find(c=>c.id===state.active)||state.companies[0];
const today=()=>new Date().toISOString().slice(0,10);
function recordActivity(){const d=today();if(!state.activity.includes(d)){state.activity.push(d);state.activity=state.activity.slice(-365)}}
function streak(){let n=0,d=new Date();while(state.activity.includes(d.toISOString().slice(0,10))){n++;d.setDate(d.getDate()-1)}return n}
function render(){const company=active(),topics=company.topics,done=topics.filter(t=>t.done).length,q=quotes[new Date().getDate()%quotes.length];$('#company-title').textContent=company.name;$('#quote').textContent=q[0];$('#quote-author').textContent=q[1];$('#today-label').textContent=new Intl.DateTimeFormat('en-IN',{weekday:'long',day:'numeric',month:'long'}).format(new Date()).toUpperCase();$('#done-count').textContent=done;$('#topic-count').textContent=topics.length;$('#progress-bar').style.width=`${topics.length?done/topics.length*100:0}%`;$('#streak-count').textContent=streak();$('#streak-copy').textContent=streak()?`You have shown up ${streak()} days in a row.`:'Complete a topic to begin.';renderCompanies();renderTopics()}
function renderCompanies(){$('#company-nav').innerHTML=state.companies.map(c=>`<button class="company-link ${c.id===state.active?'active':''}" data-company="${c.id}"><span class="nav-dot"></span>${escapeHtml(c.name)}</button>`).join('')}
function renderTopics(){const filter=$('#filter').value,query=$('#search').value.trim().toLowerCase();const topics=active().topics.filter(t=>(filter==='all'||filter==='done'&&t.done||filter==='open'&&!t.done)&&t.name.toLowerCase().includes(query));const groups=Object.entries(Object.groupBy(topics,t=>t.category));$('#topic-groups').innerHTML=groups.length?groups.map(([category,items])=>`<article class="topic-group"><button class="group-header"><span class="chevron">⌄</span><span class="category-title">${escapeHtml(category)}</span><span class="category-count">${items.filter(i=>i.done).length}/${items.length}</span></button><div class="topic-list">${items.map(t=>`<div class="topic-row"><input class="check" type="checkbox" data-check="${t.id}" ${t.done?'checked':''} aria-label="Mark ${escapeHtml(t.name)} complete"><span class="topic-name">${escapeHtml(t.name)}</span><span class="topic-actions"><button class="small-button" data-edit="${t.id}" title="Edit">✎</button><button class="small-button remove" data-remove="${t.id}" title="Remove">×</button></span></div>`).join('')}</div></article>`).join(''):'<div class="empty">No topics here yet. Add one to keep your roadmap useful.</div>'}
function escapeHtml(v){return v.replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function openTopic(t){editingId=t?.id||null;$('#topic-modal-label').textContent=t?'EDIT TOPIC':'CUSTOM TOPIC';$('#topic-modal-title').textContent=t?'Edit topic':'Add a topic';$('#topic-name').value=t?.name||'';$('#topic-category').value=t?.category||'';$('#categories').innerHTML=[...new Set(active().topics.map(x=>x.category))].map(x=>`<option value="${escapeHtml(x)}">`).join('');$('#topic-dialog').showModal();$('#topic-name').focus()}
$('#company-nav').addEventListener('click',e=>{const id=e.target.closest('[data-company]')?.dataset.company;if(id){state.active=id;save();render()}});
$('#add-company').onclick=()=>$('#company-dialog').showModal();$('#add-topic').onclick=()=>openTopic();$('#settings').onclick=()=>$('#settings-dialog').showModal();
$('#save-company').onclick=e=>{const name=$('#company-name').value.trim();if(!name){e.preventDefault();return}const master=state.companies[0];const clone=master.topics.map(t=>({...t,id:crypto.randomUUID(),done:false,completedAt:null}));const c={id:crypto.randomUUID(),name,topics:clone};state.companies.push(c);state.active=c.id;save();render();$('#company-name').value=''};
$('#save-topic').onclick=e=>{const name=$('#topic-name').value.trim(),category=$('#topic-category').value.trim()||'Other';if(!name){e.preventDefault();return}const list=active().topics;if(editingId){const t=list.find(t=>t.id===editingId);Object.assign(t,{name,category})}else list.push(newTopic(name,category));save();render()};
$('#topic-groups').addEventListener('click',e=>{const group=e.target.closest('.group-header');if(group){group.closest('.topic-group').classList.toggle('closed');return}const id=e.target.dataset.edit||e.target.dataset.remove;if(e.target.dataset.edit)openTopic(active().topics.find(t=>t.id===id));if(e.target.dataset.remove&&confirm('Remove this topic?')){active().topics=active().topics.filter(t=>t.id!==id);save();render()}});
$('#topic-groups').addEventListener('change',e=>{const id=e.target.dataset.check;if(!id)return;const t=active().topics.find(t=>t.id===id);t.done=e.target.checked;t.completedAt=t.done?today():null;if(t.done)recordActivity();save();render()});
$('#search').oninput=renderTopics;$('#filter').onchange=renderTopics;$('#expand-all').onclick=()=>document.querySelectorAll('.topic-group').forEach(g=>g.classList.remove('closed'));
function timerRender(){const m=Math.floor(timer/60),s=timer%60;$('#timer-display').textContent=`${String(m).padStart(2,'0')}:${String(s).padStart(2,'0')}`};$('#timer-start').onclick=()=>{if(timerId){clearInterval(timerId);timerId=null;$('#timer-start').textContent='Start';return}timerId=setInterval(()=>{if(--timer<=0){clearInterval(timerId);timerId=null;timer=1500;recordActivity();save();alert('Focus block complete. Nice work.');$('#timer-start').textContent='Start'}timerRender()},1000);$('#timer-start').textContent='Pause'};$('#timer-reset').onclick=()=>{timer=1500;clearInterval(timerId);timerId=null;$('#timer-start').textContent='Start';timerRender()};
$('#export-data').onclick=()=>{const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(state,null,2)],{type:'application/json'}));a.download='placement-momentum-backup.json';a.click()};$('#import-data').onchange=e=>{const file=e.target.files[0];if(!file)return;const r=new FileReader();r.onload=()=>{try{state=JSON.parse(r.result);save();render();$('#settings-dialog').close()}catch{alert('That backup file is not valid.')}};r.readAsText(file)};$('#reset-data').onclick=()=>{if(confirm('Reset every company and completion record?')){state=defaultState();save();render();$('#settings-dialog').close()}};
timerRender();render();
