'use client';
import { Fragment, useEffect, useMemo, useState } from 'react';

const quotes = [
  'Your placement season is happening now. One focused session beats worrying about the whole syllabus.',
  'Don’t wait to feel motivated. Start the timer for 25 minutes.',
  'Every topic you complete reduces what you need to worry about before the interview.',
  'Your goal isn’t perfection. Your goal is to be interview ready.',
  'One more problem. One more revision. One more step closer.',
];
const todayKey = () => new Intl.DateTimeFormat('en-CA', { timeZone: 'Asia/Kolkata', year: 'numeric', month: '2-digit', day: '2-digit' }).format(new Date());
const dateShift = (date, n) => { const d = new Date(`${date}T12:00:00+05:30`); d.setUTCDate(d.getUTCDate() + n); return new Intl.DateTimeFormat('en-CA', { timeZone: 'Asia/Kolkata', year: 'numeric', month: '2-digit', day: '2-digit' }).format(d); };
const dayKey = (date) => new Intl.DateTimeFormat('en-CA', { timeZone: 'Asia/Kolkata', year: 'numeric', month: '2-digit', day: '2-digit' }).format(new Date(date));
const fmtTime = (s) => `${String(Math.floor(s / 3600)).padStart(2, '0')}:${String(Math.floor(s / 60) % 60).padStart(2, '0')}:${String(s % 60).padStart(2, '0')}`;
const human = (s) => { const m = Math.floor(s / 60); return `${Math.floor(m / 60)}h ${m % 60}m`; };

export default function Home() {
  const [auth, setAuth] = useState(null); const [password, setPassword] = useState(''); const [loginError, setLoginError] = useState('');
  const [data, setData] = useState(null); const [error, setError] = useState(''); const [busy, setBusy] = useState(false);
  const [page, setPage] = useState('Dashboard'); const [selected, setSelected] = useState(''); const [query, setQuery] = useState(''); const [category, setCategory] = useState('All categories'); const [filter, setFilter] = useState('All topics');
  const [newTopic, setNewTopic] = useState(''); const [newCategory, setNewCategory] = useState(''); const [newCompany, setNewCompany] = useState(''); const [editingTopic, setEditingTopic] = useState(null);
  const [timerTick, setTimerTick] = useState(Date.now()); const [timerCompany, setTimerCompany] = useState(''); const [timerTopic, setTimerTopic] = useState(''); const [theme, setTheme] = useState('light');

  const request = async (body) => { const res = await fetch('/api/data', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(body) }); const json = await res.json(); if (!res.ok) throw new Error(json.error || 'Could not save your changes.'); setData(json); setTheme(json.settings.theme); setError(''); return json; };
  const load = async () => { const res = await fetch('/api/data'); if (res.status === 401) { setAuth(false); return; } const json = await res.json(); if (!res.ok) throw new Error(json.error); setData(json); setTheme(json.settings.theme); setAuth(true); setError(''); };
  useEffect(() => { fetch('/api/auth').then((r) => r.json()).then((x) => { setAuth(x.signedIn); if (x.signedIn) load().catch((e) => setError(e.message)); else if (!x.configured) setLoginError('Set AUTH_PASSWORD and SESSION_SECRET in your environment to enable private access.'); }).catch(() => setAuth(false)); }, []);
  useEffect(() => { const id = setInterval(() => setTimerTick(Date.now()), 1000); return () => clearInterval(id); }, []);
  useEffect(() => { if (data?.companies?.length && !selected) setSelected(data.companies[0]._id); if (data?.timer) { setTimerCompany(data.timer.companyId || ''); setTimerTopic(data.timer.topicId || ''); } }, [data, selected]);
  const signIn = async (e) => { e.preventDefault(); setLoginError(''); const res = await fetch('/api/auth', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ password }) }); const j = await res.json(); if (!res.ok) return setLoginError(j.error); setAuth(true); setPassword(''); load().catch((x) => setError(x.message)); };
  const logout = async () => { await fetch('/api/auth', { method: 'DELETE' }); setData(null); setAuth(false); };

  const topics = data?.topics || []; const companies = data?.companies || []; const current = companies.find((x) => x._id === selected) || companies[0];
  const progress = new Set(data?.progress || []); const sessions = data?.sessions || [];
  const sessionSeconds = (s) => s.seconds || 0;
  const totals = useMemo(() => {
    const today = todayKey(); const weekStart = dateShift(today, -6); let total = 0; let todayTotal = 0; let weekTotal = 0; const days = {};
    for (const entry of data?.studyDays || []) { const key = entry._id; const value = entry.seconds || 0; total += value; days[key] = value; if (key === today) todayTotal += value; if (key >= weekStart && key <= today) weekTotal += value; }
    return { total, today: todayTotal, week: weekTotal, days };
  }, [data?.studyDays]);
  const trackedCount = topics.length * companies.length; const completedCount = progress.size; const overallPct = trackedCount ? Math.round(completedCount * 100 / trackedCount) : 0;
  const companyDone = (companyId) => topics.filter((t) => progress.has(`${t._id}:${companyId}`)).length;
  const companyPct = (companyId) => topics.length ? Math.round(companyDone(companyId) * 100 / topics.length) : 0;
  const categories = [...new Set(topics.map((t) => t.category))];
  const groups = categories.map((name) => ({ name, topics: topics.filter((t) => t.category === name) }));
  const companyToday = totals.today;
  const streakDays = Object.entries(totals.days).filter(([, secs]) => secs >= (data?.settings.dailyGoal || 30) * 60).map(([day]) => day).sort();
  let streak = 0; for (let day = streakDays.includes(todayKey()) ? todayKey() : dateShift(todayKey(), -1); streakDays.includes(day); day = dateShift(day, -1)) streak++;
  let longest = 0; let run = 0; let previous = ''; for (const day of streakDays) { run = previous && dateShift(previous, 1) === day ? run + 1 : 1; longest = Math.max(longest, run); previous = day; }
  const companySessions = current ? sessions.filter((s) => s.companyId === current._id) : [];
  const timer = data?.timer; const elapsed = timer ? (timer.elapsedSeconds || 0) + (timer.running ? Math.max(0, Math.floor((timerTick - new Date(timer.startedAt).getTime()) / 1000)) : 0) : 0;
  const activity = sessions.filter((s) => dayKey(s.startedAt) === todayKey());
  const week = Array.from({ length: 7 }, (_, i) => { const key = dateShift(todayKey(), i - 6); return { key, label: new Date(`${key}T12:00:00+05:30`).toLocaleDateString('en', { timeZone: 'Asia/Kolkata', weekday: 'short' }), seconds: totals.days[key] || 0 }; });
  const quote = quotes[Math.floor(Date.now() / 86400000) % quotes.length];
  const toggle = async (topic, company, done) => { setData({ ...data, progress: done ? [...data.progress, `${topic._id}:${company._id}`] : data.progress.filter((x) => x !== `${topic._id}:${company._id}`) }); try { await request({ action: 'toggle', topicId: topic._id, companyId: company._id, done }); } catch (e) { setError(e.message); load(); } };
  const markNextComplete = () => { const company = companies.find((co) => co._id === selected) || companies[0]; if (!company) { setPage('Companies'); return; } const topic = topics.find((t) => !progress.has(`${t._id}:${company._id}`)); if (!topic) { setPage('Preparation'); setError(`${company.name} is fully prepared for every topic.`); return; } toggle(topic, company, true); };
  const timerAction = async (action) => {
    try {
      if (action === 'start') await request({ action: 'timer', timer: { running: true, startedAt: new Date().toISOString(), createdAt: new Date().toISOString(), elapsedSeconds: 0, companyId: timerCompany || null, topicId: timerTopic || null } });
      if (action === 'pause' && timer) await request({ action: 'timer', timer: { ...timer, running: false, elapsedSeconds: elapsed, pausedAt: new Date().toISOString() } });
      if (action === 'resume' && timer) await request({ action: 'timer', timer: { ...timer, running: true, startedAt: new Date().toISOString(), elapsedSeconds: elapsed } });
      if (action === 'stop' && timer) { if (elapsed > 0) await request({ action: 'saveSession', seconds: elapsed, startedAt: timer.createdAt || timer.startedAt, companyId: timer.companyId, topicId: timer.topicId }); else await request({ action: 'timer', timer: null }); }
      if (action === 'reset') await request({ action: 'timer', timer: null });
    } catch (e) { setError(e.message); }
  };
  const addCompany = async (e) => { e.preventDefault(); if (!newCompany.trim()) return; try { const d = await request({ action: 'addCompany', name: newCompany }); setNewCompany(''); setSelected(d.companies[d.companies.length - 1]?._id || ''); } catch (e) { setError(e.message); } };
  const addTopic = async (e) => { e.preventDefault(); if (!newTopic.trim()) return; try { await request({ action: 'addTopic', name: newTopic, category: newCategory }); setNewTopic(''); setNewCategory(''); } catch (e) { setError(e.message); } };
  const removeCompany = async (co) => { if (!window.confirm(`Delete ${co.name} and its preparation progress? Study sessions will be kept without the company link.`)) return; try { await request({ action: 'removeCompany', id: co._id }); setSelected(''); } catch (e) { setError(e.message); } };
  const removeTopic = async (topic) => { if (!window.confirm(`Delete “${topic.name}” and its company progress?`)) return; try { await request({ action: 'removeTopic', id: topic._id }); } catch (e) { setError(e.message); } };
  const saveRename = async (item, kind) => { const value = window.prompt(`Rename ${kind.toLowerCase()}`, item.name); if (!value?.trim()) return; let nextCategory = item.category; if (kind === 'Topic') { nextCategory = window.prompt('Topic category', item.category || 'Placement Preparation'); if (nextCategory === null) return; } if (value.trim() === item.name && nextCategory === item.category) return; try { await request({ action: kind === 'Company' ? 'editCompany' : 'editTopic', id: item._id, name: value.trim(), category: nextCategory }); } catch (e) { setError(e.message); } };

  if (auth === null) return <main className="boot">Loading PlacementOS…</main>;
  if (!auth) return <main className="loginPage"><section className="loginCard"><div className="brandMark">P</div><p className="eyebrow">PLACEMENTOS · PRIVATE WORKSPACE</p><h1>Your next opportunity<br/>starts with today.</h1><p className="muted">Sign in to continue your preparation tracker.</p><form onSubmit={signIn}><label>Workspace password<input type="password" autoFocus value={password} onChange={(e) => setPassword(e.target.value)} required /></label><button className="primary wide">Continue <span>→</span></button></form>{loginError && <p className="errorText">{loginError}</p>}<small>Your data is stored securely in your connected MongoDB database.</small></section></main>;

  if (!data) return <main className="boot">{error || 'Loading your workspace…'}</main>;
  const nav = ['Dashboard', 'Preparation', 'Companies', 'Topics', 'Study Timer', 'Analytics', 'Settings'];
  const visibleTopics = topics.filter((t) => (category === 'All categories' || t.category === category) && (filter === 'All topics' || (filter === 'Completed' ? progress.has(`${t._id}:${current?._id}`) : !progress.has(`${t._id}:${current?._id}`))) && t.name.toLowerCase().includes(query.toLowerCase()));
  const card = (label, value, detail, icon) => <article className="statCard" key={label}><div className="statIcon">{icon}</div><p>{label}</p><strong>{value}</strong><small>{detail}</small></article>;

  return <div className={`appShell ${theme}`}>
    <aside className="sidebar"><a className="brand" href="#dashboard"><span className="brandMark">P</span><span>placement<span className="brandLight">OS</span><small>PREPARATION WORKSPACE</small></span></a><div className="sideLabel">WORKSPACE</div><nav>{nav.map((n, i) => <button key={n} onClick={() => setPage(n)} className={page === n ? 'navItem active' : 'navItem'}><span className="navIcon">{['⌂', '▤', '◉', '▦', '◷', '⌁', '⚙'][i]}</span>{n}{n === 'Preparation' && <span className="navCount">{topics.length}</span>}</button>)}</nav><div className="sideBottom"><div className="profile"><div className="avatar">A</div><div><b>Ankita</b><small>Placement candidate</small></div><button className="iconButton" title="Sign out" onClick={logout}>↪</button></div><div className="timezone">◷ &nbsp; Asia / Kolkata</div></div></aside>
    <main className="mainArea"><header className="topbar"><div><span className="crumb">Workspace</span><span className="crumbSep">/</span><b>{page}</b></div><div className="topActions"><span className="todayLabel">{new Date().toLocaleDateString('en-IN', { timeZone: 'Asia/Kolkata', weekday: 'short', day: 'numeric', month: 'short' })}</span><button className="iconButton themeButton" title="Toggle theme" onClick={() => { const next = theme === 'dark' ? 'light' : 'dark'; setTheme(next); request({ action: 'settings', theme: next, dailyGoal: data.settings.dailyGoal }); }}>◐</button><button className="avatar mini">A</button></div></header>
      <div className="content"><div className="pageHeading"><div><p className="eyebrow">PLACEMENT PREPARATION</p><h1>{page === 'Dashboard' ? `Good ${new Date().getHours() < 12 ? 'morning' : new Date().getHours() < 17 ? 'afternoon' : 'evening'}, Ankita` : page}</h1><p className="muted">{page === 'Dashboard' ? 'Make today count. Your next opportunity is closer than you think.' : page === 'Preparation' ? 'Build confidence one topic at a time.' : page === 'Analytics' ? 'A clear view of your consistency and progress.' : 'Keep your preparation organized and moving forward.'}</p></div><div className="headingActions"><button className="outline" onClick={() => setPage('Study Timer')}>◷ &nbsp; Start study session</button><button className="primary" onClick={() => setPage('Topics')}>＋ Add topic</button></div></div>
      {error && <div className="toastError">{error}<button onClick={() => setError('')}>×</button></div>}
      {page === 'Dashboard' && <>
        <section className="hero"><div className="heroCopy"><div className="streakTag">✦ &nbsp; CONSISTENCY BUILDS OFFERS</div><h2>{streak ? `${streak} day${streak === 1 ? '' : 's'} of showing up.` : 'The next 25 minutes are yours.'}</h2><p>{quote}</p><div className="heroActions"><button onClick={() => setPage('Study Timer')} className="heroButton">Start a focus session <span>→</span></button><button className="heroTextAction" onClick={markNextComplete}>✓ &nbsp; Mark next topic</button><span className="goalHint">Daily goal · {data.settings.dailyGoal} min</span></div></div><div className="heroProgress"><div className="progressRing" style={{ '--progress': `${overallPct * 3.6}deg` }}><div><b>{overallPct}%</b><span>prepared</span></div></div><div className="ringNote"><b>{completedCount}</b> <span>topics prepared<br/>across {companies.length} companies</span></div></div><div className="heroOrb"/></section>
        <section className="statGrid">{card('Today’s study', human(totals.today), `${Math.min(100, Math.round(totals.today / (data.settings.dailyGoal * 60) * 100))}% of daily goal`, '◷')}{card('This week', human(totals.week), 'Across the last 7 days', '▥')}{card('Current streak', `${streak} days`, `${longest} day${longest === 1 ? '' : 's'} longest streak`, '✦')}{card('Companies', companies.length, `${topics.length} topics in your roadmap`, '◉')}</section>
        <div className="dashboardGrid"><section className="panel companyPanel"><div className="sectionHead"><div><h2>Company progress</h2><p>Preparation, tailored to each opportunity</p></div><button className="textButton" onClick={() => setPage('Companies')}>All companies <span>→</span></button></div>{companies.length ? <div className="companyList">{companies.slice(0, 5).map((co) => <button className="companyRow" key={co._id} onClick={() => { setSelected(co._id); setPage('Preparation'); }}><span className="companyLogo">{co.name.slice(0, 1).toUpperCase()}</span><span className="companyName"><b>{co.name}</b><small>{companyDone(co._id)} of {topics.length} topics complete</small></span><span className="companyBar"><i style={{ width: `${companyPct(co._id)}%` }}/></span><b className="companyPercent">{companyPct(co._id)}%</b><span className="arrow">↗</span></button>)}</div> : <Empty title="Your first company starts here" text="Add a company to create a dedicated preparation roadmap." action="＋ Add company" onClick={() => setPage('Companies')}/>}</section>
          <section className="panel todayPanel"><div className="sectionHead"><div><h2>Today’s activity</h2><p>Your focused work, all in one place</p></div><span className="liveDot">TODAY</span></div><div className="todayTotal"><b>{human(totals.today)}</b><span>focused today</span></div><div className="activityList">{activity.length ? activity.slice(0, 4).map((s) => <div className="activityItem" key={s._id}><span className="activityCheck">✓</span><span><b>{s.topicName || 'Study session'}</b><small>{s.companyName || 'General preparation'}</small></span><time>{human(sessionSeconds(s))}</time></div>) : <div className="emptyActivity"><span>◷</span><b>No study sessions yet</b><small>Start a focused session to build your streak.</small></div>}</div><button className="fullTextButton" onClick={() => setPage('Study Timer')}>Open study timer <span>→</span></button></section>
        </div><div className="dashboardGrid lowerGrid"><section className="panel chartPanel"><div className="sectionHead"><div><h2>Study rhythm</h2><p>Daily focus time over the last 7 days</p></div><span className="chartTotal">{human(totals.week)} <small>this week</small></span></div><div className="chart">{week.map((day) => { const max = Math.max(3600, ...week.map((x) => x.seconds)); return <div className="chartColumn" key={day.key}><span className="chartValue">{day.seconds ? human(day.seconds) : '—'}</span><div className="chartTrack"><i style={{ height: `${day.seconds ? Math.max(6, day.seconds / max * 100) : 3}%` }}/></div><small>{day.label}</small></div>; })}</div></section><section className="motivation"><span className="motivationIcon">✳</span><p className="eyebrow">A NOTE FOR TODAY</p><h2>Progress is built in the sessions nobody sees.</h2><p>Stay with the plan. Every focused hour is an investment in the conversation you’re preparing for.</p><span className="signature">YOUR FUTURE SELF</span></section></div>
      </>}

      {page === 'Preparation' && <section className="panel prepPanel"><div className="sectionHead prepHead"><div><h2>Preparation matrix</h2><p>Completion is tracked independently for every company.</p></div><div className="companySelectWrap"><label>COMPANY</label><select value={current?._id || ''} onChange={(e) => setSelected(e.target.value)}>{companies.map((co) => <option key={co._id} value={co._id}>{co.name}</option>)}</select><button className="smallPlus" onClick={() => setPage('Companies')}>＋</button></div></div>{companies.length ? <><div className="prepToolbar"><div className="searchBox"><span>⌕</span><input placeholder="Search topics..." value={query} onChange={(e) => setQuery(e.target.value)}/></div><select value={category} onChange={(e) => setCategory(e.target.value)}><option>All categories</option>{categories.map((c) => <option key={c}>{c}</option>)}</select><select value={filter} onChange={(e) => setFilter(e.target.value)}><option>All topics</option><option>Completed</option><option>Not completed</option></select><button className="viewToggle" onClick={() => setPage('Analytics')}>⊞ &nbsp; Compare all</button></div><div className="prepSummary"><span><b>{companyDone(current?._id)} / {topics.length}</b> topics complete</span><div className="summaryBar"><i style={{ width: `${companyPct(current?._id)}%` }}/></div><b>{companyPct(current?._id)}%</b></div><div className="topicGroups">{groups.map((group) => { const list = visibleTopics.filter((t) => t.category === group.name); if (!list.length) return null; const complete = group.topics.filter((t) => progress.has(`${t._id}:${current?._id}`)).length; return <section className="topicGroup" key={group.name}><div className="categoryHeading"><span>{group.name}</span><small>{complete}/{group.topics.length}</small></div>{list.map((topic) => { const checked = progress.has(`${topic._id}:${current?._id}`); return <label className="topicRow" key={topic._id}><input type="checkbox" checked={checked} onChange={(e) => toggle(topic, current, e.target.checked)}/><span className="topicTitle">{topic.name}</span><span className="topicCategory">{topic.category}</span><button className="inlineEdit" onClick={(e) => { e.preventDefault(); saveRename(topic, 'Topic'); }}>···</button></label>; })}</section>; })}</div></> : <Empty title="Add your first company" text="The master topic list is ready. Add a company to start tracking your preparation." action="＋ Add company" onClick={() => setPage('Companies')}/>}</section>}

      {page === 'Companies' && <div className="managementGrid"><section className="panel managePanel"><div className="sectionHead"><div><h2>Your companies</h2><p>Each company has its own progress and checklist.</p></div><span className="counterBadge">{companies.length} companies</span></div>{companies.length ? <div className="manageList">{companies.map((co) => <article className="manageCompany" key={co._id}><span className="companyLogo large">{co.name.slice(0, 1).toUpperCase()}</span><div className="manageCompanyInfo"><div><h3>{co.name}</h3><button className="miniLink" onClick={() => saveRename(co, 'Company')}>Rename</button><button className="miniLink danger" onClick={() => removeCompany(co)}>Delete</button></div><p>{companyDone(co._id)} completed · {topics.length - companyDone(co._id)} remaining · {human(data.companyStudy?.[co._id] || 0)} studied</p><div className="companyBar wideBar"><i style={{ width: `${companyPct(co._id)}%` }}/></div></div><strong>{companyPct(co._id)}%</strong><button className="outline compact" onClick={() => { setSelected(co._id); setPage('Preparation'); }}>Open checklist →</button></article>)}</div> : <Empty title="No companies added yet" text="Add the companies you’re preparing for. Your roadmap is ready."/>}</section><section className="panel addPanel"><div className="addIcon">＋</div><h2>Add a company</h2><p>Start a fresh, independent preparation checklist for a company.</p><form onSubmit={addCompany}><label>COMPANY NAME<input value={newCompany} onChange={(e) => setNewCompany(e.target.value)} placeholder="e.g. Google" maxLength="80" required/></label><button className="primary wide">Create company <span>→</span></button></form><small>All {topics.length} master topics will be available automatically.</small></section></div>}

      {page === 'Topics' && <div className="managementGrid"><section className="panel managePanel"><div className="sectionHead"><div><h2>Master topic list</h2><p>Edit your roadmap as your preparation evolves.</p></div><span className="counterBadge">{topics.length} topics</span></div><div className="topicManagement">{groups.map((g) => <div key={g.name}><div className="categoryHeading"><span>{g.name}</span><small>{g.topics.length} topics</small></div>{g.topics.map((t) => <div className="topicManageRow" key={t._id}><div><b>{t.name}</b><small>{t.category}</small></div><div><button className="miniLink" onClick={() => saveRename(t, 'Topic')}>Edit</button><button className="miniLink danger" onClick={() => removeTopic(t)}>Delete</button></div></div>)}</div>)}</div></section><section className="panel addPanel"><div className="addIcon">＋</div><h2>Add a topic</h2><p>Keep it quick. A topic is immediately added to each company’s checklist.</p><form onSubmit={addTopic}><label>TOPIC NAME<input value={newTopic} onChange={(e) => setNewTopic(e.target.value)} placeholder="e.g. System Design" maxLength="100" required/></label><label>CATEGORY<input list="category-options" value={newCategory} onChange={(e) => setNewCategory(e.target.value)} placeholder="e.g. Core CS"/><datalist id="category-options">{categories.map((c) => <option key={c} value={c}/>)}</datalist></label><button className="primary wide">Save topic <span>→</span></button></form></section></div>}

      {page === 'Study Timer' && <div className="timerPageGrid"><section className="panel focusPanel"><p className="eyebrow">FOCUS SESSION</p><h2>Give this time to your future.</h2><p className="muted">Your timer is saved as you go, so it follows you across pages and browser refreshes.</p><div className="timerRing"><div><strong>{fmtTime(elapsed)}</strong><span>{timer?.running ? 'SESSION IN PROGRESS' : timer ? 'SESSION PAUSED' : 'READY WHEN YOU ARE'}</span></div></div><div className="timerSelectors"><label>COMPANY<select value={timer ? timer.companyId || '' : timerCompany} disabled={!!timer} onChange={(e) => setTimerCompany(e.target.value)}><option value="">General preparation</option>{companies.map((co) => <option key={co._id} value={co._id}>{co.name}</option>)}</select></label><label>TOPIC<select value={timer ? timer.topicId || '' : timerTopic} disabled={!!timer} onChange={(e) => setTimerTopic(e.target.value)}><option value="">Choose a topic (optional)</option>{topics.map((t) => <option key={t._id} value={t._id}>{t.name}</option>)}</select></label></div><div className="timerButtons">{!timer ? <button className="primary timerStart" onClick={() => timerAction('start')}>▶ &nbsp; Start session</button> : <>{timer.running ? <button className="primary timerStart" onClick={() => timerAction('pause')}>Ⅱ &nbsp; Pause</button> : <button className="primary timerStart" onClick={() => timerAction('resume')}>▶ &nbsp; Resume</button>}<button className="outline" onClick={() => timerAction('stop')}>Stop &amp; save</button><button className="iconButton" title="Reset timer" onClick={() => window.confirm('Reset and discard this timer?') && timerAction('reset')}>↺</button></>}</div></section><section className="panel sessionAside"><h2>Your study time</h2><p>Time adds up across sessions, companies, and topics.</p><div className="timeStat"><span>Today</span><b>{human(totals.today)}</b></div><div className="timeStat"><span>This week</span><b>{human(totals.week)}</b></div><div className="timeStat"><span>All time</span><b>{human(totals.total)}</b></div><div className="dailyGoal"><div><span>Daily goal</span><b>{data.settings.dailyGoal} min</b></div><input type="range" min="5" max="120" step="5" value={data.settings.dailyGoal} onChange={(e) => request({ action: 'settings', dailyGoal: Number(e.target.value), theme })}/><small>Current streak counts a day after reaching this amount.</small></div></section></div>}

      {page === 'Analytics' && <><section className="analyticsStats">{card('Overall preparation', `${overallPct}%`, `${completedCount} of ${trackedCount} topic checks`, '◉')}{card('Completed checks', completedCount, `${trackedCount - completedCount} remaining`, '✓')}{card('Study time', human(totals.total), `${human(totals.week)} this week`, '◷')}{card('Longest streak', `${longest} days`, `${streak} days current`, '✦')}</section><section className="panel chartPanel analyticsChart"><div className="sectionHead"><div><h2>Study hours · last 7 days</h2><p>Daily study time, recorded in Asia/Kolkata</p></div><span className="chartTotal">{human(totals.week)} <small>total</small></span></div><div className="chart tallChart">{week.map((day) => { const max = Math.max(3600, ...week.map((x) => x.seconds)); return <div className="chartColumn" key={day.key}><span className="chartValue">{day.seconds ? human(day.seconds) : '—'}</span><div className="chartTrack"><i style={{ height: `${day.seconds ? Math.max(5, day.seconds / max * 100) : 2}%` }}/></div><small>{day.label}</small></div>; })}</div></section><section className="panel companyPanel analyticsCompanies"><div className="sectionHead"><div><h2>Company comparison</h2><p>Preparation coverage by company</p></div></div>{companies.length ? <div className="companyList">{companies.map((co) => <button className="companyRow" key={co._id} onClick={() => { setSelected(co._id); setPage('Preparation'); }}><span className="companyLogo">{co.name.slice(0, 1).toUpperCase()}</span><span className="companyName"><b>{co.name}</b><small>{companyDone(co._id)} complete · {topics.length - companyDone(co._id)} remaining</small></span><span className="companyBar"><i style={{ width: `${companyPct(co._id)}%` }}/></span><b className="companyPercent">{companyPct(co._id)}%</b></button>)}</div> : <Empty title="No company data yet" text="Add a company to compare preparation progress."/>}</section><section className="panel matrixPanel"><div className="sectionHead"><div><h2>Topic completion matrix</h2><p>Each company’s checklist is saved separately. Select a check to update it.</p></div></div>{companies.length ? <div className="matrixScroll"><table className="matrixTable"><thead><tr><th>TOPIC</th>{companies.map((co) => <th key={co._id} title={co.name}>{co.name}</th>)}</tr></thead><tbody>{groups.map((g) => <Fragment key={g.name}><tr className="matrixCategory"><td colSpan={companies.length + 1}>{g.name}</td></tr>{g.topics.map((topic) => <tr key={topic._id}><td>{topic.name}</td>{companies.map((co) => <td key={co._id}><input type="checkbox" aria-label={`${topic.name} for ${co.name}`} checked={progress.has(`${topic._id}:${co._id}`)} onChange={(e) => toggle(topic, co, e.target.checked)}/></td>)}</tr>)}</Fragment>)}</tbody></table></div> : <Empty title="Add a company to compare" text="Each company will appear as its own column in the preparation matrix." onClick={() => setPage('Companies')}/>}</section></>}

      {page === 'Settings' && <section className="panel settingsPanel"><div className="sectionHead"><div><h2>Workspace settings</h2><p>Personalize how PlacementOS supports your preparation.</p></div></div><div className="settingRow"><div><b>Daily study goal</b><small>Minimum study time to count toward your daily streak.</small></div><select value={data.settings.dailyGoal} onChange={(e) => request({ action: 'settings', dailyGoal: Number(e.target.value), theme })}>{[15, 20, 25, 30, 45, 60, 90, 120].map((m) => <option key={m} value={m}>{m} minutes</option>)}</select></div><div className="settingRow"><div><b>Appearance</b><small>Choose a comfortable workspace theme.</small></div><button className="outline" onClick={() => { const next = theme === 'dark' ? 'light' : 'dark'; setTheme(next); request({ action: 'settings', theme: next, dailyGoal: data.settings.dailyGoal }); }}>◐ &nbsp; Switch to {theme === 'dark' ? 'light' : 'dark'} mode</button></div><div className="settingRow"><div><b>Timezone</b><small>Used for daily progress, weeks, and streaks.</small></div><strong>Asia / Kolkata</strong></div><div className="settingRow"><div><b>Your workspace</b><small>Signed in as the owner of this private tracker.</small></div><button className="outline" onClick={logout}>Sign out</button></div></section>}
      <footer className="footer"><span>PlacementOS</span><span>Built for the work that gets you there.</span></footer></div></main><nav className="mobileNav">{nav.map((n, i) => <button key={n} className={page === n ? 'selected' : ''} onClick={() => setPage(n)}><span>{['⌂', '▤', '◉', '◷', '⌁'][i]}</span>{n === 'Study Timer' ? 'Timer' : n}</button>)}</nav></div>;
}

function Empty({ title, text, action, onClick }) { return <div className="emptyState"><span>✳</span><h3>{title}</h3><p>{text}</p>{action && <button className="primary" onClick={onClick}>{action}</button>}</div>; }
